[package]
name = "dropctrl-v3"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "0.23", features = ["esp32s3"] }
esp-println = { version = "0.13", features = ["esp32s3", "jtag-serial"] }
esp-backtrace = { version = "0.15", features = ["esp32s3", "panic-handler", "exception-handler"] }
esp-alloc = "0.6"
heapless = "0.8"
nb = "1"
embedded-hal = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
opt-level = "s"
debug = 1
incremental = false
