name: Build firmware

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install toolchain and build
        run: |
          curl -sL -o espup https://github.com/esp-rs/espup/releases/download/v0.17.1/espup-x86_64-unknown-linux-gnu
          chmod +x espup
          ./espup install -t esp32s3 -f export-esp.sh
          . export-esp.sh
          rustc --version
          cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3
          path: target/xtensa-esp32s3-none-elf/release/dropctrl-v3
